### ISSUE TITLE
How do we correct misunderstandings/lack of knowledge?

### ISSUE THREAD

**Issue by elimisteve** [ksimka/go-is-not-good#12]
> You're writing some code. And suddenly you understand you need something that language can't give you. You go here and check if you're the one with that issue or not. If it's a common issue, it'll be here. Then you decide what to do: choose another tool for your task or go find a better solution or a workaround.

What if it's common to do something in Go incorrectly, and that's what people are complaining about?  This would be a great venue to teach people the better way, perhaps by adding links or comments just after certain complaints.  Will you accept PRs that help clarify such issues?  Thanks.

**Comment by thedrow** [comment]
That will help new Go programmers like me understand how to resolve issues better.

**Comment by ksimka** [comment]
@elimisteve I think it's simply impossible, it'll end up with another holy war. We all have our own opinions. One will always complain about a thing another wouldn't even think of. Every problem is unique and can be solved in many ways. "To do something incorrectly" — `corectness` is a soooo relative term. I.e. I don't agree with some arguments listed here, but authors think they're 100% right, and they have a right to think so :)
