### ISSUE TITLE
Add Go Bloviations from fish shell maintainer

### ISSUE THREAD

**Issue by AlekSi** [ksimka/go-is-not-good#24]
http://ridiculousfish.com/blog/posts/go_bloviations.html

**Comment by ksimka** [comment]
Site looks dead (Cloudflare shows 522), so I'll use http://webcache.googleusercontent.com/search?q=cache:bOUEgIg5epYJ:ridiculousfish.com/blog/posts/go_bloviations.html+&cd=1&hl=en&ct=clnk&gl=en for now.

**Comment by ksimka** [comment]
Done. Thanks.

**Comment by AlekSi** [comment]
Hm, http://ridiculousfish.com/blog/posts/go_bloviations.html works for me. 😕

**Comment by ksimka** [comment]
For me too now, magic... Replaced it. Thanks.
