### ISSUE TITLE
Missing entry: No math.abs methods for anything that is not float

### ISSUE THREAD

**Issue by lital-lb** [ksimka/go-is-not-good#34]
No article, had to go to IRC to ask about it.

Here's the stdlib implementation where only the float version exist. Happy casting
https://golang.org/src/math/abs.go

Solution? Implement the appropriate abs methods yourself
Why? "Go creators work in mysterious ways" - someone told to me on the IRC channel

**Comment by dgryski** [comment]
This and the sorting issue probably fall under `no generics`.

**Comment by ksimka** [comment]
> No article

But you can write your own and make a PR.
