### ISSUE TITLE
tags are arbitrary strings, no compiler checked syntax

### ISSUE THREAD

**Issue by n4zukker** [ksimka/go-is-not-good#50]
Pop quiz.  What's wrong with this:
> ``json:"foo.omitempty"`

The language should have put some structure on tags.  Instead of opening a loophole where weird syntax can be added and conventional values are not checked.  The compiler or linter should have at least warned that there's a period where a comma should be.

**Comment by ksimka** [comment]
This repo is not about complaining in issues, sorry.

**Comment by n4zukker** [comment]
Ok.  I'll make a PR.  I saw that just now at the bottom of the repo.
