### ISSUE TITLE
this-repo-not-so-good

### ISSUE THREAD

**Issue by TheFern2** [ksimka/go-is-not-good#67]
95% of the articles are from a decade ago, most written after golang was a few years old. Quite a few items have been fixed. Not saying golang is perfect but if there's going to be a repo bashing a language at least keep it updated with relevant articles.

**Comment by onlyjob** [comment]
What's wrong with old articles? Did language evolve (or reform) enough to invalidate early impressions/observations?

Perhaps you could expand on what have been fixed?
