### ISSUE TITLE
http://byrd.im/go-is-poor/

### ISSUE THREAD

**Issue by redelpedron** [ksimka/go-is-not-good#9]
-Go is a poorly designed language
* Slice manipulations are broken
* Sometimes nil interfaces are not entirely nil
* Funny variable shadowing
* No first-class support for interfaces
* Questionable compiler rigidity
* Go generate is a quirk

Author: Ian Byrd

**Comment by ksimka** [comment]
It's already here, added by Ian itself. Thanks anyway.
